Entities/Node.cs
namespace TreeV2.Entities
{
    public class Node
    {
        public int Id { get; set; }
        public string Name { get; set; } // name of node
        public string? ParentNode { get; set; } // branch
        public List<Node> Children { get; set; } = new List<Node>(); // leaves
    }
}

Models/ErrorViewModel.cs
namespace TreeV2.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/TreeController.cs
using Microsoft.AspNetCore.Mvc;
using TreeV2.NodeDto;
using TreeV2.Interfaces;

namespace TreeV2.Controllers
{
    public class TreeController : Controller
    {
        private readonly ITreeService _treeService;

        public TreeController(ITreeService treeService)
        {
            _treeService = treeService;
        }

        public async Task<IActionResult> Delete(int id)
        {
            var result = await _treeService.DeleteNodeById(id);

            if (!result.Success)
            {
                return RedirectToAction("Index", new { message = result.Message });
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateNodeDto dto)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index", new { message = "Error" });
            }

            var result = await _treeService.CreateNode(dto);

            if (!result.Success)
            {
                return RedirectToAction("Index", new { message = result.Message });
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditNodeDto dto)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index", new { message = "Error" });
            }

            var result = await _treeService.EditNode(dto);

            if (!result.Success)
            {
                return RedirectToAction("Index", new { message = result.Message });
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Index(string? message)
        {
            if (!string.IsNullOrEmpty(HttpContext.Request.Query["sort"]))
            {
                HttpContext.Session.SetString("sort", HttpContext.Request.Query["sort"]);
            }

            ViewData["Message"] = message;
            ViewData["Sort"] = HttpContext.Session.GetString("sort");

            var nodes = await _treeService.GetAllNodesOrderedById();

            return View(nodes);
        }
    }
}

Views/Shared/Index.cshtml
@using TreeV2.NodeDto
@model IList<TreeV2.Entities.Node>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "TreeV2";
}

<script src="https://cdn.jsdelivr.net/npm/vue@2.6.14/dist/vue.js"></script>

<div class="w-100 text-center bg-danger">
    @ViewData["Message"]
</div>

<div class="d-flex" id="app">
    <div class="w-25">
        @{
            var createNodeDto = new CreateNodeDto()
            {
                Parent = Model.ToList().ConvertAll(i => new SelectListItem()
                {
                    Text = i.Id + ". " + i.Name,
                    Value = i.Id.ToString(),
                    Selected = false
                })
            };
            await Html.RenderPartialAsync("_CreateForm", createNodeDto);
        }

    </div>
    <div class="w-75">
        @{
            var editNodeDto = new EditNodeDto()
            {
                Nodes = Model.ToList()
            };

            await Html.RenderPartialAsync("_EditForm", editNodeDto);
        }
    </div>
</div>

<script>
    var vueApp = new Vue({
        el: '#app',
        data: {
        },
        methods: {
            toggle: (e) => {
                let list = e.target.parentNode.querySelector("ul").style;
                list.display != "none" ? list.display = "none" : list.display = "block";
            },

            foldList: (e) => {
                let nodes = document.querySelectorAll("#root ul");
                for (node of nodes) {
                    node.style.display = "none";
                }
            },

            unfoldList: (e) => {
                let nodes = document.querySelectorAll("#root ul");
                for (node of nodes) {
                    node.style.display = "block";
                }
            },
        }
    })
</script>

Views/Shared/_CreateForm.cshtml
@model TreeV2.NodeDto.CreateNodeDto
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@using (Html.BeginForm("Create", "Tree", FormMethod.Post, new { @class = "d-flex flex-column" }))
{
    <h3>Create</h3>
    <div class="d-flex flex-column">
        @Html.LabelFor(m => m.Name)
        @Html.TextBoxFor(m => m.Name, new { @class="w-75"})
    </div>
    <div class="d-flex flex-column">
        @Html.LabelFor(m => m.Parent)
        @if (Model is not null)
        {
            @Html.DropDownListFor(m => m.ParentNode, Model.Parent, "Choose Parent", new { @class="w-75"})
        }
    </div>
    <input type="submit" class="w-75 mt-3" />
}

Views/Shared/_EditForm.cshtml
@model TreeV2.NodeDto.EditNodeDto
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@functions {
    private void ShowTree(TreeV2.Entities.Node node)
    {
        <li>
            @if (node.Children.Count != 0)
            {
                <span class="bi bi-folder-fill" v-on:click="toggle($event)" style="cursor:pointer"></span>
            }
            else
            {
                <span class="bi bi-folder" style="cursor:not-allowed"></span>
            }
            <label>
                @Html.RadioButtonFor(m => m.SelectedId, node.Id.ToString())
                @node.Id.
                @node.Name
            </label>
            @Html.ActionLink("", "Delete", "Tree", new { id = node.Id }, new { @class = "bi bi-trash-fill text-decoration-none text-reset" })
            @if (node.Children.Count != 0)
            {
                <ul style="list-style: none">
                    @if (ViewData["Sort"]?.ToString() == "Name")
                    {
                        @foreach (var child in node.Children.OrderBy(n => n.Name))
                        {
                            ShowTree(child);
                        }
                    }
                    else
                    {
                        @foreach (var child in node.Children)
                        {
                            ShowTree(child);
                        }
                    }
                </ul>
            }
        </li>
    }
}

@if (Model.Nodes.FirstOrDefault() is not null)
{
    @using (Html.BeginForm("Edit", "Tree", null, FormMethod.Post, true, new { @class = "d-flex flex-row" }))
    {
        <div class="w-25 d-flex flex-column">
            <h3>Edit</h3>
            @Html.LabelFor(m => m.Name)
            @Html.TextBoxFor(m => m.Name)
            @Html.LabelFor(m => m.ParentNode)
            @Html.DropDownListFor(m => m.ParentNode, new SelectList(Model.Nodes.Select(m=>m.Id + ". " + m.Name)), "Choose Parent")
            <input type="submit" class="mt-3" />
        </div>
        <div class="w-75">
            <div class="d-flex mb-3">
                <button class="btn btn-primary w-50 m-2" type="button" v-on:click="foldList($event)">Fold list</button>
                <button class="btn btn-primary w-50 m-2" type="button" v-on:click="unfoldList($event)">Unfold list</button>

                <button class="btn btn-primary w-50 m-2" type="button" v-on:click="moveUp">
                    <span class="bi bi-arrow-up-circle"></span> Move Up
                </button>
                <button class="btn btn-primary w-50 m-2" type="button" v-on:click="moveDown">
                    <span class="bi bi-arrow-down-circle"></span> Move Down
                </button>
            </div>
            <div>
                <ul style="list-style:none" id="root">
                    @{
                        ShowTree(Model.Nodes.First());
                    }
                </ul>
            </div>
        </div>
    }
    <div class="d-flex" style="margin-left: 25%;">
        @Html.ActionLink("Sort by Id", "Index", "Tree", new { sort = "Id"}, new { @class="btn btn-primary w-50 m-2"})
        @Html.ActionLink("Sort by Name", "Index", "Tree", new { sort = "Name"}, new { @class="btn btn-primary w-50 m-2"})
    </div>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Tree.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Tree" asp-action="Index">TreeV2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1"> </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Zadanie Rekrutacyjne 
        </div>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>